//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCreator.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TestCreatorEntities : DbContext
    {
        public TestCreatorEntities()
            : base("name=TestCreatorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Stanowiska> Stanowiska { get; set; }
        public virtual DbSet<Testy> Testy { get; set; }
        public virtual DbSet<Uzytkownicy> Uzytkownicy { get; set; }
    
        public virtual ObjectResult<SysUsersContener> GetAllUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SysUsersContener>("GetAllUsers");
        }
    }
}
